In [1]:
import numpy as np  

In [3]:
mylist = [1,2,3]

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
nested_list = [[1,2],[3,4],[5,6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(2)

array([0.94359838, 0.81024413])

In [24]:
np.random.rand(3,4)

array([[0.73926183, 0.98929933, 0.23256109, 0.06453589],
       [0.29813374, 0.94890618, 0.08020811, 0.84507613],
       [0.44522567, 0.8414364 , 0.97536985, 0.28129605]])

In [26]:
np.random.randn(5,5)

array([[ 1.54608153,  1.51426286,  0.91656692, -0.17042262,  0.82203652],
       [ 0.64594467, -0.47435748,  0.6286807 , -0.82850675, -1.31506001],
       [-0.05241715,  1.06511846, -0.04515874,  1.41101495, -0.9171242 ],
       [-0.26794882,  0.91621088,  1.80205215, -1.46067844,  0.44706116],
       [ 1.46384573,  1.60274979, -0.98013479,  0.25041681,  1.59847684]])

In [33]:
np.random.randint(1,100,(15,3)) ##gerar um valor aleatório dentro de um range

array([[ 8, 61, 92],
       [53, 69, 27],
       [42, 89, 47],
       [83, 76, 71],
       [17, 30, 26],
       [96, 76, 96],
       [45, 74, 33],
       [ 8, 24, 92],
       [66, 61, 99],
       [39, 61, 34],
       [71, 47, 54],
       [91, 41, 21],
       [49, 36, 19],
       [58, 87, 38],
       [37, 99,  7]])

In [36]:
np.random.seed(42)
np.random.rand(4)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [38]:
arr = np.arange(25)

In [41]:
ranarr = np.random.randint(0,50,10)

In [43]:
arr.shape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [44]:
arr.shape

(25,)

In [47]:
 arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [49]:
ranarr.max() #Max Value

43

In [50]:
ranarr.argmax()   #Index of Max value

7

In [52]:
ranarr.min() #min value

1

In [54]:
ranarr.argmin() # Index of Min Value

5

In [55]:
ranarr.dtype

dtype('int64')

In [57]:
myarr = np.random.rand(4)

In [58]:
myarr

array([7.78765841e-04, 9.92211559e-01, 6.17481510e-01, 6.11653160e-01])