<h3> 6 -<b>NumPy Array<b> <h3>


In [ ]:
import numpy as np  

In [ ]:
mylist = [1,2,3]

In [ ]:
np.array(mylist)

In [ ]:
nested_list = [[1,2],[3,4],[5,6]]

In [ ]:
np.array(nested_list)

In [ ]:
np.arange(0,10)

In [ ]:
np.arange(0,11,2)

In [ ]:
np.zeros(3)

In [ ]:
np.zeros((4,10))

In [ ]:
np.ones(3)

In [ ]:
np.ones((4,4))

In [ ]:
np.linspace(0,10,21)

In [ ]:
np.eye(5)

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(3,4)

In [ ]:
np.random.randn(5,5)

In [ ]:
np.random.randint(1,100,(15,3)) ##gerar um valor aleatório dentro de um range

In [ ]:
np.random.seed(42)
np.random.rand(4)


In [ ]:
np.random.rand(4)

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
arr.shape

In [ ]:
ranarr

In [ ]:
arr.shape

In [64]:
 arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

In [ ]:
ranarr.max() #Max Value

In [ ]:
ranarr.argmax()   #Index of Max value

In [ ]:
ranarr.min() #min value

In [ ]:
ranarr.argmin() # Index of Min Value

In [ ]:
ranarr.dtype

In [ ]:
myarr = np.random.rand(4)

In [ ]:
myarr

<h1> 7 - NumPy Index Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [16]:
slice_off_arr = arr[0:5]

In [17]:
slice_off_arr

array([0, 1, 2, 3, 4])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_off_arr[:] = 99

In [20]:
slice_off_arr

array([99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

In [24]:
arr_copy[:]=100

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d.shape

(3, 3)

In [51]:
arr_2d[0,2]

15

In [56]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr = np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
bool_arr = arr>4

In [68]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

<h1> Numpy Operation <h1>

In [2]:
import numpy as np

In [5]:
arr = np.arange(0,10)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.log(arr)

/tmp/ipykernel_5456/2931416741.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr.sum()

45

In [19]:
arr.mean()

4.5

In [20]:
arr.max()

9

In [21]:
arr.var()

8.25

In [24]:
arr.std()

2.8722813232690143

In [31]:
arr2d = np.arange(0,25).reshape(5,5)

In [34]:
arr2d.shape

(5, 5)

In [36]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr2d.sum()

300

In [42]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [43]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

<h1> NumPy Exercises <h1>
<h2> Nivel 1: Básico <h2>


<h2> <b> 1 - Criação de Arrays <h2>


Import numpy as np

In [44]:
import numpy as np

Crie um array de números inteiros de 1 a 10.

In [48]:
arr = np.arange(0,10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Crie um array de zeros com tamanho 5 e um array de uns com tamanho 5.

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Crie um array com valores de 10 a 50, com um passo de 5 entre os valores.

In [59]:
np.linspace(10,50,9)

array([10., 15., 20., 25., 30., 35., 40., 45., 50.])

<h2> <b> 2 - Indexação e Slicing <h2>

Dado um array de números de 1 a 20, selecione os valores de índice 3 a 8.

In [123]:
arr= np.arange(1,21)

In [124]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [125]:
arr[2:8]

array([3, 4, 5, 6, 7, 8])

Inicie com um array np.arange(1, 11). Extraia apenas os números pares.

In [126]:
arr = np.arange(1,11)

In [127]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
pares = arr[1::2]

In [129]:
pares

array([ 2,  4,  6,  8, 10])

Use slicing para alterar todos os valores de índice par para -1.

In [130]:
arr[::2] = -1

In [131]:
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

<h2> <b> 3 - Operações Matemáticas Simples <h2>

Crie dois arrays de 5 números aleatórios e calcule a soma, subtração, multiplicação e divisão entre eles.

In [159]:
arr = np.random.rand(5)

In [165]:
arr2 = np.random.rand(5)

In [166]:
arr

array([0.60320185, 0.14998905, 0.74970869, 0.69622974, 0.85353469])

In [167]:
arr2

array([0.41488547, 0.42123653, 0.74973276, 0.7252647 , 0.89077439])

In [168]:
arr + arr2

array([1.01808732, 0.57122557, 1.49944146, 1.42149443, 1.74430908])

In [169]:
arr - arr2

array([ 1.88316373e-01, -2.71247484e-01, -2.40699852e-05, -2.90349592e-02,
       -3.72397030e-02])

In [170]:
arr * arr2

array([0.25025968, 0.06318086, 0.56208117, 0.50495085, 0.76030685])

In [171]:
arr / arr2

array([1.45389965, 0.35606847, 0.9999679 , 0.9599664 , 0.95819401])

Dado um array np.array([10, 20, 30, 40, 50]), adicione 5 a cada elemento e divida cada um por 10.

In [180]:
arr3 = np.array([10,20,30,40,50])

In [181]:
resultado = (arr3 + 5)/10

In [182]:
resultado

array([1.5, 2.5, 3.5, 4.5, 5.5])