<h3> 6 -<b>NumPy Array<b> <h3>


In [ ]:
import numpy as np  

In [ ]:
mylist = [1,2,3]

In [ ]:
np.array(mylist)

In [ ]:
nested_list = [[1,2],[3,4],[5,6]]

In [ ]:
np.array(nested_list)

In [ ]:
np.arange(0,10)

In [ ]:
np.arange(0,11,2)

In [ ]:
np.zeros(3)

In [ ]:
np.zeros((4,10))

In [ ]:
np.ones(3)

In [ ]:
np.ones((4,4))

In [ ]:
np.linspace(0,10,21)

In [ ]:
np.eye(5)

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(3,4)

In [ ]:
np.random.randn(5,5)

In [ ]:
np.random.randint(1,100,(15,3)) ##gerar um valor aleatório dentro de um range

In [ ]:
np.random.seed(42)
np.random.rand(4)


In [ ]:
np.random.rand(4)

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
arr.shape

In [ ]:
ranarr

In [ ]:
arr.shape

In [64]:
 arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

In [ ]:
ranarr.max() #Max Value

In [ ]:
ranarr.argmax()   #Index of Max value

In [ ]:
ranarr.min() #min value

In [ ]:
ranarr.argmin() # Index of Min Value

In [ ]:
ranarr.dtype

In [ ]:
myarr = np.random.rand(4)

In [ ]:
myarr

<h1> 7 - NumPy Index Selection

In [3]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [16]:
slice_off_arr = arr[0:5]

In [17]:
slice_off_arr

array([0, 1, 2, 3, 4])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_off_arr[:] = 99

In [20]:
slice_off_arr

array([99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

In [24]:
arr_copy[:]=100

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d.shape

(3, 3)

In [51]:
arr_2d[0,2]

15

In [56]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr = np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
bool_arr = arr>4

In [68]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])